export const DEMO_SCENARIOS = [
  {
    name: "Normal Payment",
    description: "A regular, low-risk domestic payment",
    icon: "CheckCircle",
    color: "green",
    input: {
      amount: 2500,
      currency: "INR",
      paymentMethod: "UPI",
      country: "IN",
      isNewDevice: false,
      accountAgeDays: 365,
      previousFailedAttempts: 0,
      transactionsInLast5Min: 0,
      isDisposableEmail: false,
      isSuspiciousIp: false,
    },
  },
  {
    name: "Suspicious Payment",
    description: "Medium risk: unusual amount from a new device",
    icon: "AlertTriangle",
    color: "yellow",
    input: {
      amount: 25000,
      currency: "INR",
      paymentMethod: "CREDIT_CARD",
      country: "IN",
      isNewDevice: true,
      accountAgeDays: 90,
      previousFailedAttempts: 1,
      transactionsInLast5Min: 1,
      isDisposableEmail: false,
      isSuspiciousIp: false,
    },
  },
  {
    name: "Account Takeover",
    description: "New device, new location, unusual spending",
    icon: "UserX",
    color: "orange",
    input: {
      amount: 75000,
      currency: "INR",
      paymentMethod: "CREDIT_CARD",
      country: "US",
      isNewDevice: true,
      accountAgeDays: 180,
      previousFailedAttempts: 3,
      transactionsInLast5Min: 2,
      isDisposableEmail: false,
      isSuspiciousIp: false,
    },
  },
  {
    name: "Card Testing Attack",
    description: "Many small transactions in rapid succession",
    icon: "CreditCard",
    color: "red",
    input: {
      amount: 100,
      currency: "INR",
      paymentMethod: "CREDIT_CARD",
      country: "NG",
      isNewDevice: true,
      accountAgeDays: 1,
      previousFailedAttempts: 8,
      transactionsInLast5Min: 12,
      isDisposableEmail: true,
      isSuspiciousIp: true,
    },
  },
  {
    name: "Velocity Attack",
    description: "High-value transactions at extreme speed",
    icon: "Zap",
    color: "red",
    input: {
      amount: 100000,
      currency: "INR",
      paymentMethod: "DEBIT_CARD",
      country: "IN",
      isNewDevice: true,
      accountAgeDays: 3,
      previousFailedAttempts: 5,
      transactionsInLast5Min: 10,
      isDisposableEmail: false,
      isSuspiciousIp: false,
    },
  },
  {
    name: "Impossible Travel",
    description: "Transaction from unexpected country after recent domestic activity",
    icon: "Globe",
    color: "orange",
    input: {
      amount: 45000,
      currency: "USD",
      paymentMethod: "CREDIT_CARD",
      country: "RU",
      isNewDevice: true,
      accountAgeDays: 200,
      previousFailedAttempts: 2,
      transactionsInLast5Min: 1,
      isDisposableEmail: false,
      isSuspiciousIp: true,
    },
  },
] as const;

export type DemoScenario = (typeof DEMO_SCENARIOS)[number];
